#!/usr/bin/env python3
# reads the given directory and all it's subdirectories then prints them out in the list

from sys import argv
import os

#fuction which is using os.walk method to walk through the give directory structure
def print_dir(path):
    all_files = os.walk(path)
    for file in all_files:
        print(f'in directory {file[0]} :')
        print(f'the catalogs: {", ".join([folder for folder in file[1]])}')
        print(f'the files: {", ".join([file_name for file_name in file[2]])}')
        print('-'*40)

#try to handle the situation of the script arguments mismatch
try:
    script_name, path = argv
except ValueError:
    print ('There is no parameter(s). The internal data which is located in the script will be used.')
    path = '.'
else:
    print (f'parameters are {path}')

#checks if the given path exists
if os.path.isdir(path):
    print(f'''trying to read {path} and all it's subdirectories''')
    print()
    print_dir(path)
else:
    print(f'Invalid parameter. the directory {path} is not exist')
