#!/usr/bin/env python3
# reads the given directory and all it's subdirectories then prints them out in the list

from sys import argv
import os

#recursive function to walk through the "path" directory tree
def print_dir(path):
    print('-'*40)
    print(f'in {path} :')
    for f in os.listdir(path):
        if os.path.isdir(f'{path}/{f}'):
            print(f'{f}/')
            print_dir(f'{path}/{f}')
        else:
            print(f'{f}')

#try to catch arguments mismatching
try:
    script_name, path = argv
except ValueError:
    print ('There is no parameter(s). The internal data which is located in the script will be used.')
    path = '.'
else:
    print (f'parameters are {path}')

#checks if the given path exists
if os.path.isdir(path):
    print(f'''trying to read {path} and all it's subdirectories''')
    print()
    print_dir(path)
else:
    print(f'Invalid parameter. the directory {path} is not exist')
